#-------------------------------------------------------------
# AltSettings config
#-------------------------------------------------------------
#玩家上線是否提醒GM
WHO_ONLINE_MSG_ON = True
#-------------------------------------------------------------
#交易等級限制
trade_level = 45
#交倉庫使用等級限制
dwarf_level = 15
#-------------------------------------------------------------
#奪魂特效編號(設0關閉特效) 原本編號(11677) 防具class檔案ElitePlateMail_Fafurion
soul_hp_gfx = 11677
#反彈特效編號(設0關閉特效) 原本編號(10710) 防具class檔案Death_Pant
death_pant_gfx = 10710
#-------------------------------------------------------------
# ----- 大喊 -----------
GM_OVERHEARD2 = True

#GM偷聽對話功能 True=是, False=否
# ----- 密語 -----------
GM_OVERHEARD = True
# ----- 一般 -----------
GM_OVERHEARD0 = True
# ----- 血盟 -----------
GM_OVERHEARD4 = True
# ----- 組隊 -----------
GM_OVERHEARD11 = True
# ----- 聯盟 -----------
GM_OVERHEARD13 = True
#-------------------------------------------------------------
# 萬能藥使用限制(數量)
Medicine = 6

# 萬能藥使用限制(能力值上限)
MedicinePower = 45

# 能力值上限
Power = 45
#-------------------------------------------------------------
# 是否允許丟棄道具至地面true允許 false不允許
dorpitem = false
#-------------------------------------------------------------
#公頻廣播等級限制
GlobalChatLevel = 50
#-------------------------------------------------------------
#密語等級限制
WhisperChatLevel = 5
#-------------------------------------------------------------
#設定自動取得道具的方式0-掉落地上, 1-掉落寵物身上, 2-掉落角色身上
AutoLoot = 2

#MOB物品掉落地面距離限制(超過設置距離掉落地面)
LootingRange = 15
#-------------------------------------------------------------
# 允許pk
NonPvP = True

# 執行pk處分
Punishment = false
#-------------------------------------------------------------
#聯盟系統開關  True to On, False to Off
ClanAlliance = true
#-------------------------------------------------------------
# 地面道具清除時間(單位;分鐘)
# 1-60
# 設置為0不清除
ItemDeletionTime = 5
#-------------------------------------------------------------
# WHO 顯示 額外設置
WhoCommandx = true

# WHO 顯示 額外設置方式 0:對話視窗顯示 1:視窗顯示
# 這一項設置必須在WhoCommandx = true才有作用
Who_type = 1

# WHO 顯示 人數增值(倍率)
WhoCommandcount = 3
#-------------------------------------------------------------
#攻城戰中死亡是否損失經驗值
WarPunishment = False

#攻城戰時間(d:日 h:時 m:分)
WarTime = 1h

#攻城戰間隔(d:日 h:時 m:分)
WarInterval = 7d
#-------------------------------------------------------------
#設定 是否使用範圍性怪物刷新...True=是, False=否
SpawnHomePoint = true

#設定 怪物刷新的範圍大小。
SpawnHomePointRange = 8

#SpawnHomePointCount、SpawnHomePointDelay 設定迴避適用出生點 (不適用於首領怪等等) 
#適用出生點設定最小 count (2的話，count 只有2以上 spawnlist 設定出生點)
SpawnHomePointCount = 2

#適用出生點設定的最大 min_respawn_delay (100的話，min_respawn_delay 只有100以下 spawnlist 設定出生點)
SpawnHomePointDelay = 100
#-------------------------------------------------------------
# 元素石產生數量
ElementalStoneAmount = 1
#-------------------------------------------------------------
#盟屋稅金的支付期限(日)
HouseTaxInterval = 10
#-------------------------------------------------------------
#最大娃娃攜帶量
MaxDollCount = 1
MaxDollCount2 = 0
#-------------------------------------------------------------
#轉生娃娃攜帶量1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
MAX_DOLL_METE = 5,1,1,1,1,1,1,1,1,01,01,01,01,01,02,02,02,02,02,02
#-------------------------------------------------------------
# NPC(Summon, Pet)背包最大容量
MaxNpcItem = 12
#-------------------------------------------------------------
# 個人倉庫容許收容數量
MaxPersonalWarehouseItem = 150

# 血盟倉庫容許收容數量
MaxClanWarehouseItem = 200
#-------------------------------------------------------------
# 指定刪除保留7天時間等級
DeleteCharacterAfterLV = 60

# 指定等級刪除保留7天時間
DeleteCharacterAfter7Days = False
#-------------------------------------------------------------
# NPC死亡後刪除時間(單位:秒)
NpcDeletionTime = 5
#-------------------------------------------------------------
# 初始可建立人物數量
DefaultCharacterSlot = 8
#-------------------------------------------------------------
#轉生系統

#  ---轉生所需等級---
MeteLevel = 99
#  ---最大允許轉生次數---
MeteMaxCount = 10
#  ---每次轉生血量保留 (%數)---
MeteRemainHp = 30
#  ---每次轉生魔量保留 (%數)---
MeteRemainMp = 30
#  ---系統是否給予返生藥水---
MeteGivePotion = true
#-------------------------------------------------------------
#師徒系統 by terry0412

#  ---啟動開關---
ApprenticeSwitch = False
#  ---XX級(含)以上的角色才可成為師父；未達XX級的角色才可成為徒弟---
ApprenticeLevel = 70
#  ---師徒組隊中，師父將額外獲得徒弟打怪經驗值加成 (每組一個徒弟+XX%)---
ApprenticeExpBonus = 3
#  ---徒弟達到指定等級後,畢業可獲得的道具編號 (守護傳承之鍊)---
ApprenticeItemId = 30336
#-------------------------------------------------------------
#最高可組隊人數
MaxPT = 20
#-------------------------------------------------------------
# [龍之鑰匙限制可開啟地圖清單] (請填入地圖編號) (如要輸入多項請以逗號隔開) by terry0412
DragonKeyMapList = 340,350,360,370,800,4
#-------------------------------------------------------------
#魔族武器保護卷軸
#  ---強化成功機率 (強化值增加1)---
ElyosEnchantSuccess = 1
#-------------------------------------------------------------
#歐林的飾品強化卷軸(受祝福卷軸強化失敗時不會倒扣)
#  ---強化成功機率 (強化值增加1)---
#普通飾品強化卷軸幾率
OrimEnchantSuccess = 3
#受祝福飾品強化卷軸幾率
OrimEnchantSuccessbless = 5
#-------------------------------------------------------------
# [可丟給怪物的道具清單] (請填入道具編號) (如要輸入多項請以逗號隔開) by terry0412
GiveItemList = 40010,40011,40012,40013,40018,40056,40057,40060,40070,40032,82203,82204,41423,41424,88,40508,40045,40749,40750,40751,40752,40753,40754,40755,40756,40757,40758,40759,40760,40761,40762,40763,40764,40765,40766,41310
#-------------------------------------------------------------
#不會觸發定時外掛檢測的地圖(已迴避城堡戰爭區域及盟屋區域、世界樹下)
NoAIMapList = 340,350,360,370,666,800,8014,5300,16384,16896,17408,17920,18432,18944,19456,19968,20480,20992,21504,22016,22528,23040,23552,24064,24576,25088,41
#-------------------------------------------------------------
#新版記憶座標清單 
#  ---初始記憶座標數量上限---
CharBookInitCount = 60

#  ---最大可擴充次數上限 (每次擴充可提高上限10個)---
#CharBookMaxCharge = 4
#-------------------------------------------------------------
#是否開啟贊助紅利給予道具
Dividend = false
#贊助紅利給予道具編號
DividendItem = 40308
#贊助紅利給予道具數量
DividendQuantityCount = 1
#贊助多少給予道具
DividendQuantity = 1000
#-------------------------------------------------------------
#是否啟用過多少安定廣播系統
enchantoverTF =  True

#武器過安定值多少就廣播
enchantovertell1 = 3

#防具過安定值多少就廣播
enchantovertell2 = 3

#衝裝公告顯示(設定0=對話框,設定1=畫面中間)
enchantoverType = 0

#武器多少強化值後無法使用武捲強化
enchantweapon = 15

#防具多少強化值後無法使用防捲強化
enchanarmor = 10
#-------------------------------------------------------------
#自訂義回魔區設定
#回血量
costom_hpr = 30
#回魔量
costom_mpr = 30
#地圖定義
costom_mapid = 12150
#-------------------------------------------------------------
# 攻城旗幟內是否禁止攜帶召幻獸  true:禁止 false:允許
WAR_summon = true
#-------------------------------------------------------------
#守護者名稱設定
Protector_Name = ***守護者***
#-------------------------------------------------------------
#轉生後是否公告 (轉生藥水使用後)
ReincarnationBroad = true
#-------------------------------------------------------------
# GM上線是否自動隱身
# false = 不啟用 true = 啟用
GmHide = false
#-------------------------------------------------------------
#連線獎勵等級限制
onlinegiftlevel = 80
#-------------------------------------------------------------
# 掉寶公告是否顯示螢幕 false=顯示於聊天視窗 true=顯示於螢幕
BOX_BROAD_SCREEN = true

# 殺人公告是否顯示螢幕 false=顯示於聊天視窗 true=顯示於螢幕
KILL_BROAD_SCREEN = true
#-------------------------------------------------------------
#是否啟動組隊同地圖經驗加成
partyexp = true
#同地圖組隊人數1~10人 1人增加多少%經驗
partynum10 = 10
#同地圖組隊人數11~20人 1人增加多少%經驗
partynum20 = 20
#同地圖組隊人數21~30人以上 1人增加多少%經驗
partynum30 = 50
#等級需大於幾等才可獲得經驗加成
partyexplv = 60
#-------------------------------------------------------------
#武器加成特效 

#  ---特效延遲時間 (單位:秒) (設置0 = 關閉)---
WeaponEffectDelay = 0
#  ---武器額外持續特效1 (過1)---
WeaponEffect1 = -1
#  ---武器額外持續特效2 (過2)---
WeaponEffect2 = -1
#  ---武器額外持續特效3 (過3)---
WeaponEffect3 = 20302
#  ---武器額外持續特效4 (過4)---
WeaponEffect4 = 14033
#  ---武器額外持續特效5 (過5)---
WeaponEffect5 = 14032
#  ---武器額外持續特效6 (過6)---
WeaponEffect6 = 14030
#  ---武器額外持續特效7 (過7)---
WeaponEffect7 = 14871
#  ---武器額外持續特效8 (過8)---
WeaponEffect8 = 14034
#  ---武器額外持續特效9 (過9)---
WeaponEffect9 = 20350
#  ---武器額外持續特效10 (過10)---
WeaponEffect10 = 20314
#  ---武器額外持續特效11 (過11)---
WeaponEffect11 = 20314
#  ---武器額外持續特效12 (過12)---
WeaponEffect12 = 20314
#  ---武器額外持續特效13 (過13)---
WeaponEffect13 = 20314
#  ---武器額外持續特效14 (過14)---
WeaponEffect14 = 20314
#  ---武器額外持續特效15 (過15)---
WeaponEffect15 = 20314
#  ---武器額外持續特效16 (過16)---
WeaponEffect16 = 20314
#  ---武器額外持續特效17 (過17)---
WeaponEffect17 = 20314
#  ---武器額外持續特效18 (過18)---
WeaponEffect18 = 20314
#  ---武器額外持續特效19 (過19)---
WeaponEffect19 = 20314
#  ---武器額外持續特效20 (過20)---
WeaponEffect20 = 20314
#  ---武器額外持續特效21 (過21)---
WeaponEffect21 = 4572
#  ---武器額外持續特效22 (過22)---
WeaponEffect22 = 4572
#  ---武器額外持續特效23 (過23)---
WeaponEffect23 = 4572
#  ---武器額外持續特效24 (過24)---
WeaponEffect24 = 4572
#  ---武器額外持續特效25 (過25)---
WeaponEffect25 = 4572
#  ---武器額外持續特效26 (過26)---
WeaponEffect26 = 4572
#  ---武器額外持續特效27 (過27)---
WeaponEffect27 = 4572
#  ---武器額外持續特效28 (過28)---
WeaponEffect28 = 4572
#  ---武器額外持續特效29 (過29)---
WeaponEffect29 = 4572
#  ---武器額外持續特效30 (過30)---
WeaponEffect30 = 4572
#-------------------------------------------------------------
#  ---是否開啟---
WeaponPower = true
#  ---各階段強化值附加傷害---
WeaponPower09 = 2
WeaponPower10 = 4
WeaponPower11 = 6
WeaponPower12 = 8
WeaponPower13 = 10
WeaponPower14 = 12
WeaponPower15 = 14
WeaponPower16 = 16
WeaponPower17 = 18
WeaponPower18 = 24
WeaponPower19 = 31
WeaponPower20 = 40
#-------------------------------------------------------------
#玩家出生公告 (false = 不公告)
NewCreate = false
#-------------------------------------------------------------
#角色出生座標 (格式: locx, locy, mapid) (設置 null 則啟動內建出生座標) 
#奇岩33438,32811,4
#新手克勞斯32772,32819,7783
#GM房間32736,32800,99

NewCharLoc = 32730,32811,3
#-------------------------------------------------------------
#boss水晶失敗是否變回1(true=失敗扣1,false=失敗不倒扣)
DE_BOSS = false

#Boss水晶是否不同類型可以直接覆蓋 (True=是 Flase=否)
Cross_BOSS = True
#-------------------------------------------------------------