#-------------------------------------------------------------
# 闖關 BOSS 館設定（NPC 編號 6100000）
#-------------------------------------------------------------
# 是否一天只能進入一次（會使用 questid；true=啟用，false=停用）
room_1_day = true
# 任務編號
questid = 30001
# 任務編號重置時間（格式：hh:mm:ss）
questid_reset_time = 23:59:30
#-------------------------------------------------------------
# 參加等級門檻
QuestLevel = 50
#-------------------------------------------------------------
# 參加所需物品
itemid = 44070
# 物品數量
itemcount = 50
#-------------------------------------------------------------
# 怪物是否掉落物品（true=不掉落，false=掉落）
storedroped = false
#-------------------------------------------------------------
# 小怪數量
MobIdCount = 1
#-------------------------------------------------------------
# 第一關
# 小怪編號
MobId1 = 45684
# BOSS 編號
BossId1 = 45602
#-------------------------------------------------------------
# 第二關
# 小怪編號
MobId2 = 45621
# BOSS 編號
BossId2 = 45602
#-------------------------------------------------------------
# 第三關
# 小怪編號
MobId3 = 45621
# BOSS 編號
BossId3 = 45602
#-------------------------------------------------------------
# 第四關
# 小怪編號
MobId4 = 45621
# BOSS 編號
BossId4 = 45602
#-------------------------------------------------------------
# 第五關
# 小怪編號
MobId5 = 45621
# BOSS 編號
BossId5 = 45602
#-------------------------------------------------------------
# 第六關
# 小怪編號
MobId6 = 45621
# BOSS 編號
BossId6 = 45602
#-------------------------------------------------------------
# 第七關
# 小怪編號
MobId7 = 45621
# BOSS 編號
BossId7 = 45602
#-------------------------------------------------------------
# 第八關
# 小怪編號
MobId8 = 45621
# BOSS 編號
BossId8 = 45602
#-------------------------------------------------------------
# 第九關
# 小怪編號
MobId9 = 45621
# BOSS 編號
BossId9 = 45602
#-------------------------------------------------------------
# 第十關
# 小怪編號
MobId10 = 45621
# BOSS 編號
BossId10 = 45602
#-------------------------------------------------------------