#-------------------------------------------------------------
# BOSS館設置 NPC編號-6100001
#-------------------------------------------------------------
# 啟動是否公告 true是，flase否
StartShowWorld = flase
# 清潔完是否公告
CleanShowWorld = flase
#-------------------------------------------------------------
# 參加等級
BossLevel = 50
# 最低人數
BossPlayermin = 1
# 最高人數
BossPlayermax = 5
#-------------------------------------------------------------
# 等待時間(秒) +核心倒數10秒
BossStartTime = 5
# 小怪召喚間隔時間(秒)
BossMobTime = 5
# BOSS召喚間隔時間(秒)
BossTime = 6
# 最後一關BOSS召完等待多久結束(秒)
BossEndTime = 10
# 清館時間(秒)
CleantimeSet = 20
#-------------------------------------------------------------
# 進入所需道具編號
BossIdItemId = 44070
# 道具數量
BossIdItemCount = 10
#-------------------------------------------------------------
# BOSS館地圖座標X
bosslocx = 32865
# BOSS館地圖座標Y
bosslocy = 32640
# BOSS館地圖編號
bossmapid = 511
#-------------------------------------------------------------
# 小怪數量
MobIdCount = 5
#-------------------------------------------------------------
# 第一關
# 小怪編號
MobId1 = 45621
# BOSS編號
BossId1 = 45602
#-------------------------------------------------------------
# 第二關
# 小怪編號
MobId2 = 45621
# BOSS編號
BossId2 = 45602
#-------------------------------------------------------------
# 第三關
# 小怪編號
MobId3 = 45621
# BOSS編號
BossId3 = 45602
#-------------------------------------------------------------
# 第四關
# 小怪編號
MobId4 = 45621
# BOSS編號
BossId4 = 45602
#-------------------------------------------------------------
# 第五關
# 小怪編號
MobId5 = 45621
# BOSS編號
BossId5 = 45602
#-------------------------------------------------------------
# 第六關
# 小怪編號
MobId6 = 45621
# BOSS編號
BossId6 = 45602
#-------------------------------------------------------------
# 第七關
# 小怪編號
MobId7 = 45621
# BOSS編號
BossId7 = 45602
#-------------------------------------------------------------
# 第八關
# 小怪編號
MobId8 = 45621
# BOSS編號
BossId8 = 45602
#-------------------------------------------------------------
# 第九關
# 小怪編號
MobId9 = 45621
# BOSS編號
BossId9 = 45602
#-------------------------------------------------------------
# 第十關
# 小怪編號
MobId10 = 45621
# BOSS編號
BossId10 = 45602
#-------------------------------------------------------------