# =================================================================
# Character config
# =================================================================
#
PrinceMaxHP = 3000
PrinceMaxMP = 1200
KnightMaxHP = 4300
KnightMaxMP = 800
ElfMaxHP = 3200
ElfMaxMP = 1800
WizardMaxHP = 2700
WizardMaxMP = 2600
DarkelfMaxHP = 3000
DarkelfMaxMP = 1600
DragonKnightMaxHP = 3400
DragonKnightMaxMP = 1100
IllusionistMaxHP = 3100
IllusionistMaxMP = 2000
WarriorMaxHP = 4200
WarriorMaxMP = 1000