#-------------------------------------------------------------
# givevip.properties  潘朵拉商城消費給予VIP狀態
#-------------------------------------------------------------
# 是否開啟潘朵拉商城消費多少給予VIP狀態  true開啟，flase不開啟
give_vip = true
#-------------------------------------------------------------
# (第1組)
# 消費【大於等於(give_vip_price_1)以及小於(give_vip_price_2)】給予VIP狀態
give_vip_price_1 = 1000
# 給予VIP狀態等級
give_vip_level_1 = 1
# 給予VIP狀態時間(日)
give_vip_day_1 = 30
#-------------------------------------------------------------
# (第2組)
# 消費【大於等於(give_vip_price_2)以及小於(give_vip_price_3)】給予VIP狀態
give_vip_price_2 = 3000
# 給予VIP狀態等級
give_vip_level_2 = 2
# 給予VIP狀態時間(日)
give_vip_day_2 = 30
#-------------------------------------------------------------
# (第3組)
# 消費【大於等於(give_vip_price_3)以及小於(give_vip_price_4)】給予VIP狀態
give_vip_price_3 = 8000
# 給予VIP狀態等級
give_vip_level_3 = 3
# 給予VIP狀態時間(日)
give_vip_day_3 = 30
#-------------------------------------------------------------
# (第4組)
# 消費【大於等於(give_vip_price_4)以及小於(give_vip_price_5)】給予VIP狀態
give_vip_price_4 = 15000
# 給予VIP狀態等級
give_vip_level_4 = 4
# 給予VIP狀態時間(日)
give_vip_day_4 = 30
#-------------------------------------------------------------
# (第5組)
# 消費【大於等於(give_vip_price_5)】給予VIP狀態
give_vip_price_5 = 20000
# 給予VIP狀態等級
give_vip_level_5 = 5
# 給予VIP狀態時間(日)
give_vip_day_5 = 30
#-------------------------------------------------------------