#-------------------------------------------------------------
# ipcheck.properties
#-------------------------------------------------------------

# IP封包驗證策略(當本項設定為TRUE後續各項設置均會被忽略)
IPCHECKPACK = false

#-------------------------------------------------------------

# 啟用IP檢查策略
# 串連設定
IPCHECK = false

# 相同IP指定秒數內重複連結列入計算(毫秒)
# 指定秒數內重複連結 錯誤次數+1
TIMEMILLIS = 90000

# 達到指定次數切斷相同IP所有連線
COUNT = 300

# 達到指定次數是否封鎖IP並寫入資料庫(true:是 false:否)
SETDB = false

# 如果是LINUX系統 是否加入ufw 封鎖清單(true:是 false:否)
# 這設置對WINDOWS系統無效果
# 這設置 必須SETDB = true 才有效果
UFW = false

#-------------------------------------------------------------

# 1個IP僅允許一個連線
ISONEIP = false

#-------------------------------------------------------------

#1個IP只定時間內僅允許連限一個(毫秒) 0:不啟用
ONETIMEMILLIS = 0
#-------------------------------------------------------------
#同帐号重覆登入侦测时间间隔 (单位：秒)
ACCLOGINTIMEMILLIS = 10
#要是侦测到帐号重覆登入，是否直接把该帐号IP封锁？ True=是, False=否
ACCLOGINBANIP = False
#-------------------------------------------------------------