#-------------------------------------------------------------
# other.properties
#-------------------------------------------------------------
# 殷海薩龍之祝福指數最大值設置 核心預設500
LEAVES_MAXEXP = 1500
#-------------------------------------------------------------
# 劍靈狀態圖示編號
Weapon_Soul_IconId = 5223
# 劍靈狀態圖示訊息編號
Weapon_Soul_StringId = 2174
#-------------------------------------------------------------
# Tam幣系统-多少秒獲得1次Tam幣(單位：秒)
Tam_Time = 600
# Tam幣系統-1次獲得多少Tam幣(會乘以玩家開通的數量，比如設10000，玩家開通2個號就是20000個，最多隻能開通3個)
TAM_COUNT = 10000
#-------------------------------------------------------------
# 重置轉生天賦需要的道具
ReiItemId = 44070
# 重置轉生天賦需要的道具數量
ReiItemCount = 200
# 是否開啟使用轉生藥水給予天賦點數 true開啟，flase不開啟
ReiPoint = true
# 轉生藥水增加相應轉生天賦點數(1轉-20轉)
ReiPoinMete = 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
# 轉生天賦點數上限(轉生天賦點數多少後使用轉生藥水不加天賦點數)
ReiPointUp = 20
# 全職第一項天賦技能等級上限
ReiPointLv_1 = 5
# 全職第二項天賦技能等級上限
ReiPointLv_2 = 6
# 全職第三項天賦技能等級上限
ReiPointLv_3 = 7
#-------------------------------------------------------------
# 是否開啟攻城召喚紅騎士團  true開啟(妖魔 奇岩 肯特 空城不召喚 玩家拿了城的才召喚 )，flase不開啟
red_knight = true
# 參加紅騎士團等級 (有城堡的玩家等級到了也不能加入)
red_knight_lv = 70
#-------------------------------------------------------------
# 是否開啟升級經驗獎勵狀態 (3小時) true開啟，flase不開啟
level_up = flase
# 開啟後多久級給予經驗獎勵狀態 (官方60級)
level_up_lv = 60
# 開啟後升級經驗獎勵狀態經驗倍數  (官方1.23)
level_up_exp = 1.23
#-------------------------------------------------------------
# 潘朵拉銅像使用道具
Statue_Magic_ItemId = 40308
# 潘朵拉銅像使用扣除道具數量
Statue_Magic_ItemCount = 10000

# 潘朵拉銅像指定輔助魔法ID 要依次對應Statue_Magic_SkillTime時間
Statue_Magic_SkillId = 14,26,42,43,79,115,158
# 潘朵拉銅像指定輔助魔法時間
Statue_Magic_SkillTime = 1800,1200,1200,1200,1200,640,320

# 潘朵拉銅像是否補滿血量
Statue_Magic_Maxhp = true
#-------------------------------------------------------------
# 娃娃合成幾率設置 (1-4級娃娃共用)
# 2個娃娃合成幾率
dollsize2_chance = 10
# 3個娃娃合成幾率
dollsize3_chance = 20
# 4個娃娃合成幾率
dollsize4_chance = 35
#-------------------------------------------------------------
# 娃娃大成功幾率 (成功跳級 1跳3 2跳4 3跳5)
doll_chance_big = 10
#-------------------------------------------------------------
# [火焰之魔杖限制可開啟地圖清單] (請填入地圖編號) (如要輸入多項請以逗號隔開)
iceKeyMapList = 2100,2101,2151
#-------------------------------------------------------------
#商幣比值
changecount = 20000
#-------------------------------------------------------------
# Boss強度加成
bosspower = 2
bosshit = 25
#-------------------------------------------------------------
#巴雕製作機率控制
r_83055 = 1000000

#銀幣轉移控制等級
r_80033 = 85
#-------------------------------------------------------------
# 允許玩家解散血盟，true允許，flase不允許，
clanadel = true

# 允許盟員自行建立封號
clanatitle = true

# 自行建立血盟人數上限
# 設置為0時 依照官方設置
clancount = 0
#-------------------------------------------------------------
# 啟用人物全時光照(true啟用 false關閉)
light = true
#-------------------------------------------------------------
# 百分百武卷最高可追加值
weapon100 = 15

# 百分百防卷最高可追加值
armor100 = 10
#-------------------------------------------------------------
# 顯示怪物血條
hpbar = true
#-------------------------------------------------------------
# 一般商店是否顯示詳細訊息
shopinfo = true
#-------------------------------------------------------------
# 旅館HP恢復增加
innhpr = 1

# 旅館MP恢復增加
innmpr = 1

# 妖森HP恢復增加
foresthpr = 1

# 妖森MP恢復增加
forestmpr = 1

# 血盟小屋HP恢復增加
homehpr = 1

# 血盟小屋MP恢復增加
homempr = 1

# 城堡HP恢復增加
castlehpr = 1

# 城堡MP恢復增加
castlempr = 1
#-------------------------------------------------------------
# 廣播扣除 指定道具 或是 飽食度 (0:飽食度    其他:指定道具編號)
set_global = 40308

# 廣播扣除質(set_global設置0:扣除飽食度量    set_global設置其他:扣除指定道具數量)
set_global_count = 1000

# 廣播/買賣頻道間隔秒數
set_global_time = 5
#-------------------------------------------------------------
# 經驗值顯示虛擬倍數
# 經驗值設定500倍 這裡設置2玩家會看到1000倍
rate_xp_who = 1
#-------------------------------------------------------------
# 怪物是否主動攻擊紅人
kill_red = true
#-------------------------------------------------------------
# 戰鬥特化遭遇的守護等級(官方預設20)
# 設置等級以下角色 被超過10級以上的玩家攻擊而死亡時，不會失去經驗值，也不會掉落物品
encounter_lv = 35
#-------------------------------------------------------------
#元寶偵測紀錄 
#  ---啟動開關---
AdenaCheckSwitch = true
#  ---每XX秒判斷一次---
AdenaCheckTimeSec = 5
#  ---差異數量達到多少以上才紀錄
AdenaCheckCountDiffer = 300
#-------------------------------------------------------------
# 攻城旗幟內是否允許攜帶娃娃  true:允許 false:禁止
war_doll = true
#-------------------------------------------------------------
#當VIP道具(weight輸入0時) 階級達到多少時顯示時間為1年(作為永久VIP使用)
VIP_level = 1
#-------------------------------------------------------------
#伊薇版本血盟技能 所需道具數量(server_event id:9)
#綁定對應道具[641655]
clanskillitem1 = 500
#綁定對應道具[641656]
clanskillitem2 = 500
#綁定對應道具[641657]
clanskillitem3 = 500
#-------------------------------------------------------------
#王族等級需大於幾等才能創立血盟
clancreatelv = 10

#王族等級需大於幾等才能宣戰
clanforwarlv = 70
#-------------------------------------------------------------
#是否開放給其他人看見[陣營稱號]&[轉聲稱號]
ShowSpTitle = false
#-------------------------------------------------------------

######PVP系統########(一次性所有武器PVP  true:開 false:關)(2017/05/12取消掉)

PVP_WEAPON = true

#加多少後PVP+1
PVP_plus = 9


######PVP系統########(一次性所有防具PVP  true:開 false:關)
PVP_ARMOR = false

#加多少後PVP+1
PVP_plus2 = 6

#----------防爆倒扣&歸零捲---------------

#武器保護卷軸 上限
ElyosEnchant = 16

#防具保護卷軸 上限
Elyos2Enchant = 10

#-------殺BOSS領取物品-----------

(等級限制)(quest2.Npc_Conquest 與 quest2.Npc_Conquest2)
Npc_Conquest = 50
			
Npc_Conquest2 = 50

#------------掃街系統--------------

#  ---隨機掃街啟動開關---
FreeFightSwitch = false
#  ---隨機掃街死亡掉落道具最高數量 (最低固定為1)---
FreeFightMaxDrop = 3
#  ---隨機掃街時段(24小時制 00:00~23:59) ---
FreeFightTimeList = 01:00
#  ---隨機掃街持續時間 (單位:小時)---
FreeFightRemainTime = 2
#  ---隨機掃街地圖抽取張數 (將隨機抽選A~B張地圖出來掃街)---
FreeFightMapChoice = 1-2
#  ---隨機掃街地圖列表 (逗號區隔)---
FreeFightMapList = 1,2
#  ---隨機掃街死亡掉落裝備機率 (善惡值高於或等於0的玩家)---
FreeFightDropChanceA = 100
#  ---隨機掃街死亡掉落裝備機率 (善惡值低於0的玩家)---
FreeFightDropChanceB = 100

# ---每日任務重置 (格式: hh:mm:ss)---
QuestSetResetTime = 23:59:50

#限時地圖重置時間(mapids_group)23:55
Reset_Map_Time = 23:59:50

# ---媽祖狀態重置 (格式: hh:mm:ss)---
MazuResetTime = 23:59:50

# -------------- 加速器偵測功能 --------------

# PunishmentType: 懲罰機制類型
# 0:剔除遊戲   1:鎖定人物(自訂)秒   2:傳到地獄 PunishmentTime(自訂) 秒後傳回
PunishmentType = 1
PunishmentTime = 5
PunishmentMap = 666
# 設定不正常封包數值,滿足條件則切斷連線
InjusticeCount = 8
# 設定如果參雜正常封包在不正常封包中,數值滿足時 InjusticeCount歸 0
JusticeCount = 12
# 加速器檢查嚴密度(攻擊),為免除錯誤檢測設定數值允許幾%加速。(如果常常誤報，請將數值稍微調大)106
CheckStrictness = 150
# 加速器檢查嚴密度(移動),為免除錯誤檢測設定數值允許幾%加速。(如果常常誤報，請將數值稍微調大)106
CheckMoveStrictness = 150

#===自創陣營戰系統===#
#報名道具編號
RedBlueJoin_itemid = 40308
#報名道具數量
RedBlueJoin_count = 5000000
#每隊報名人數
RedBluePc_amount = 1
#最低等級限制
RedBlueLv_min = 80
#最高等級限制
RedBlueLv_max = 99
#進行時間
RedBlueTime_all = 60
#清理時間
RedBlueTime_clear = 60
#凍結時間
RedBlueEffect_time = 10
#結束後傳送座標
RedBlueEnd_map = 32800,32927,800
#房間1 紅隊入場座標
RedBlueRed_map1 = 32772,32815,10502
#房間1 藍隊入場座標
RedBlueBlue_map1 = 32772,32974,10502
#房間2 紅隊入場座標
RedBlueRed_map2 = 32686,32881,95
#房間2 藍隊入場座標
RedBlueBlue_map2 = 32713,32909,95
#初始積分
RedBlueStart_point = 10
#擊殺敵方成員積分
RedBlueNormal_point = 1
#擊殺敵方隊長積分
RedBlueLeader_point = 5
#獎勵道具編號
RedBlueBonus_itemid = 641427
#獎勵道具數量
RedBlueBonus_count = 500
#當日可領取幾次對戰獎勵
RedBlueReward_times = 5

#對戰獎勵重置時間 (格式: hh:mm:ss)---
RedBlueReward_RESET_TIME = 23:59:50


#----------底比斯大戰爭霸遊戲---------------

# 是否開啟遊戲 true:開 false:關
Mini_Siege = true

# 開啟底比斯大戰遊戲NPC召喚時間 (格式: hh:mm:ss) 風木村莊倉庫旁邊
# 如果伺服器開啟時間比設置的晚 那伺服器開啟時就直接開啟底比斯大戰遊戲
minisiege_starttime = 19:00:00

# 遊戲結束後下次開啟召喚NPC(次元之門)時間 (分)
MiniSiege_NextTime = 600

# 遊戲NPC(存在or報名or等待)時間 (秒)
MiniSiege_ReadyTime = 1800

# 遊戲時間 (秒)
MiniSiege_PlayTime = 3600

# 遊戲最少人數
MiniSiege_MinPlayer = 3

# 玩家摧毀守護塔-同陣營獎勵道具
A_TowerItemId = 40308
# 玩家摧毀守護塔-同陣營獎勵道具數量
A_TowerItemCount = 100000

# 玩家摧毀中塔-同陣營獎勵道具
B_TowerItemId = 40308
# 玩家摧毀中塔-同陣營獎勵道具數量
B_TowerItemCount = 200000

# 最終獲勝陣營獎勵道具
C_TowerItemId = 40308
# 最終獲勝陣營獎勵道具數量
C_TowerItemCount = 300000

# 最終召喚BOSS編號(給獲勝陣營擊殺) 可複數多個(,)隔開
MiniSiege_BossId = 46123,46124

#pc等级低于多少怪物攻击降低
pclevel=55

#怪物物理伤害减低多少 2就是减少一半
guiwugjbl=4

#怪物魔法伤害减低多少 2就是减少一半
guiwugjblmf=4

#-----------------------
# 2個1級娃娃合成時機率
DollLv1_Size2_Chance = 5
# 3個1級娃娃合成時機率
DollLv1_Size3_Chance = 12
# 4個1級娃娃合成時機率
DollLv1_Size4_Chance = 20
# ------------------------
# 2個2級娃娃合成時機率
DollLv2_Size2_Chance = 5
# 3個2級娃娃合成時機率
DollLv2_Size3_Chance = 12
# 4個2級娃娃合成時機率
DollLv2_Size4_Chance = 20
# ------------------------
# 2個3級娃娃合成時機率
DollLv3_Size2_Chance = 5
# 3個3級娃娃合成時機率
DollLv3_Size3_Chance = 12
# 4個3級娃娃合成時機率
DollLv3_Size4_Chance = 20
# ------------------------
# 2個4級娃娃合成時機率
DollLv4_Size2_Chance = 2
# 3個4級娃娃合成時機率
DollLv4_Size3_Chance = 5
# 4個4級娃娃合成時機率
DollLv4_Size4_Chance = 10
# ------------------------


# ------------------------
# 2個11級其它道具合成時機率
ItemLv11_Size2_Chance = 5
# 3個11級其它道具合成時機率
ItemLv11_Size3_Chance = 12
# 4個11級其它道具合成時機率
ItemLv11_Size4_Chance = 20
# ------------------------
# 2個12級其它道具合成時機率
ItemLv12_Size2_Chance = 5
# 3個12級其它道具合成時機率
ItemLv12_Size3_Chance = 12
# 4個12級其它道具合成時機率
ItemLv12_Size4_Chance = 20
# ------------------------
# 2個13級其它道具合成時機率
ItemLv13_Size2_Chance = 5
# 3個13級其它道具合成時機率
ItemLv13_Size3_Chance = 12
# 4個13級其它道具合成時機率
ItemLv13_Size4_Chance = 20
# ------------------------
# 2個14級其它道具合成時機率
ItemLv14_Size2_Chance = 5
# 3個14級其它道具合成時機率
ItemLv14_Size3_Chance = 12
# 4個14級其它道具合成時機率
ItemLv14_Size4_Chance = 20
# ------------------------
# 2個15級其它道具合成時機率
ItemLv15_Size2_Chance = 5
# 3個15級其它道具合成時機率
ItemLv15_Size3_Chance = 12
# 4個15級其它道具合成時機率
ItemLv15_Size4_Chance = 20
# ------------------------
# 2個16級其它道具合成時機率
ItemLv16_Size2_Chance = 2
# 3個16級其它道具合成時機率
ItemLv16_Size3_Chance = 5
# 4個16級其它道具合成時機率
ItemLv16_Size4_Chance = 10
# ------------------------
# 娃娃大成功幾率 (成功跳級 1跳3 2跳4 3跳5)
doll_chance_big = 0

# ------------------------
#商店限購重置時間 A時 B分
daibuytimeA = 23
daibuytimeB = 55

# ------------------------
#內掛可使用時間 18-28不能掛機
BotStartHour = 23
BotEndHour = 18
