#-------------------------------------------------------------
# quest.properties
#-------------------------------------------------------------
# 每日獎勵等級限制(設0不判斷)
day_reward_level = 0
# 每日獎勵VIP等級限制(設0不判斷)
day_reward_levelvip = 0
# 每日獎勵轉生等級限制(設0不判斷)
day_reward_levelmet = 0
# 每日獎勵道具
day_reward_item = 40308:1000,40308:10000,40308:100000
# 每日獎勵任務編號
day_reward_questId = 35553
# 每日獎勵任務編號重置時間(格式: hh:mm:ss)
day_reward_reset_time = 23:58:30
#-------------------------------------------------------------
#寶1區任務
# --- 任務等級 ---
# --- 所需轉身數 ---
# --- 冒號(:)區隔 -> 道具ID和數量 ---
# --- 逗號(,)區隔 -> 多筆資料輸入 ---
Bao1_Quest_Lv = 50
Bao1_Quest_Levelmet = 0
Bao1_Quest_Item = 40010:100
# --- 寶1任務石身上最大數量 ---
Bao1_Stone_MaxCount = 100

#寶2區任務
# --- 任務等級 ---
Bao2_Quest_Lv = 90
Bao2_Quest_Levelmet = 0
Bao2_Quest_Item = 44070:500
Bao2_Stone_MaxCount = 500

#寶3區任務
# --- 任務等級 ---
Bao3_Quest_Lv = 90
Bao3_Quest_Levelmet = 0
Bao3_Quest_Item = 44070:100
Bao3_Stone_MaxCount = 100

#寶4區任務
# --- 任務等級 ---
Bao4_Quest_Lv = 95
Bao4_Quest_Levelmet = 0
Bao4_Quest_Item = 44070:500
Bao4_Stone_MaxCount = 500

#寶5區任務
# --- 任務等級 ---
Bao5_Quest_Lv = 95
Bao4_Quest_Levelmet = 0
Bao5_Quest_Item = 44070:500
Bao5_Stone_MaxCount = 500