# =================================================================
# 一般倍率設定
# =================================================================
# 可填整數或小數
# 經驗倍率（0.0-32767.0）
RateXp = 300.0

# 假日經驗加成
RateXpWeek = 50

# 正義倍率（0.0-32767.0）
RateLawful = 1.0

# 友好倍率（0.0-32767.0）
RateKarma = 5.0

# 金幣掉落倍率（0.0-127.0）
RateDropAdena = 10.0

# 假日金幣加成
RateDropAdenaWeek = 5

# 道具掉落倍率（0.0-32767.0）
RateDropItems = 1.0

# 假日道具掉落倍率（0.0-32767.0）
RateDropItemsWeek = 0.5

# 武器與防具強化成功率
EnchantChanceWeapon = 2
EnchantChanceArmor = 2

# 屬性強化成功率（%）
AttrEnchantChance = 8

# 角色負重倍率（0.0-127.0）
RateWeightLimit = 10.0

# 寵物負重倍率（0.0-127.0）
RateWeightLimitforPet = 1.0 

# 寵物經驗倍率（0.0-32767.0）
RateXpPet = 100.0

# 寵物最高等級限制（1-99）
PetHighLevel = 99

# 商店販賣價格倍率（0.0-127.0）
RateShopSellingPrice = 1.0

# 商店收購價格倍率（0.0-127.0）
RateShopPurchasingPrice = 1.0

# 道具生成率（%）
# 航海日誌
CreateChanceDiary = 67
# 凈化藥水
CreateChanceRecollection = 50
# 神秘藥水
CreateChanceMysterious = 50
# 加工後的寶石
CreateChanceProcessing = 50
# 加工後的鑽石
CreateChanceProcessingDiamond = 50
# 丹特斯召喚球
CreateChanceDantes = 50
# 古代護身符
CreateChanceAncientAmulet = 60
# 封印的歷史書
CreateChanceHistory = 6
