# =================================================================
# NORMAL RATES
# =================================================================
#整數值で指定（少數點以下も指定可能）
# Rate control
#經驗倍率 0.0-32767.0
RateXp = 300.0

#假日增加經驗
RateXpWeek = 50

#正義倍率 0.0-32767.0
RateLawful = 1.0

#友好倍率 0.0-32767.0
RateKarma = 5.0

#金幣倍率 0.0-127.0
RateDropAdena = 10.0

#假日金幣
RateDropAdenaWeek = 5

#道具倍率 0.0-32767.0
RateDropItems = 1.0

#假日道具倍率 0.0-32767.0
RateDropItemsWeek = 0.5

#武防倍率
EnchantChanceWeapon = 2
EnchantChanceArmor = 2

# 屬性強化成功率 %で指定
AttrEnchantChance = 8

#角色負重倍率 0.0-127.0
RateWeightLimit = 10.0

#寵物負重倍率 0.0-127.0
RateWeightLimitforPet = 1.0 

#寵物經驗倍率 0.0-32767.0
RateXpPet = 100.0

#寵物限制最高等級 1-99
PetHighLevel = 99

#商店販賣價格倍率 0.0-127.0
RateShopSellingPrice = 1.0

#商店收購價格倍率 = 0.0-127.0
RateShopPurchasingPrice = 1.0

# item生成率 %で指定
#航海日誌
CreateChanceDiary = 67
#凈化のポーション
CreateChanceRecollection = 50
#ミステリアスポーション
CreateChanceMysterious = 50
#加工された寶石
CreateChanceProcessing = 50
#加工されたダイアモンド
CreateChanceProcessingDiamond = 50
#ダンテスの召還球
CreateChanceDantes = 50
#古代のアミュレット
CreateChanceAncientAmulet = 60
#封印された歷史書 
CreateChanceHistory = 6
