#-------------------------------------------------------------
# 記錄設定
#-------------------------------------------------------------

# 是否記錄強化失敗的物品（true=記錄，false=不記錄）
LoggingBanEnchant = true

# 是否記錄人物對話
# 一般頻道：LoggingChatNormal
LoggingChatNormal = true

# 大叫頻道：LoggingChatShout
LoggingChatShout = true

# 世界頻道：LoggingChatWorld
LoggingChatWorld = true

# 血盟頻道：LoggingChatClan
LoggingChatClan = true

# 密語頻道：LoggingChatWhisper
LoggingChatWhisper = true

# 隊伍頻道：LoggingChatParty
LoggingChatParty = true

# 交易頻道：LoggingBusiness
LoggingBusiness = true

# 聯盟頻道：LoggingChatCombined
LoggingChatCombined = true

# 隊伍頻道（第二類）：LoggingChatChatParty
LoggingChatChatParty = true
