#-------------------------------------------------------------
# skills.properties - 技能傷害設置
#-------------------------------------------------------------
*************法師****************

#光裂兩次機率(1=1%)
DISINTEGRATE_RND = 1

#法師新技能 治癒逆行施法機率設定
DEATH_HEAL = 90

************幻術師***************

#幻術 - 化身技能承受傷害(數字越高自己被打的傷害越高)
ILLUSION_AVATAR_DAMAGE = 1

#幻術 - 疼痛的歡愉最大傷害限制
JOY_OF_PAIN_DMG = 3000

#骷髏破壞的命中機率設定
#最高設定為100(命中機率)
Skulldamage = 20

***********龍騎士****************

#屠宰衝暈機率(1=1%)
FOE_SLAYER_RND = 1

#屠宰衝暈秒數(1000=1秒)
FOE_SLAYER_SEC = 1000

# 弱點曝光相關設定
# 弱點曝光階段Lv1【設定】= 增加的傷害
Vulnerability1 = 10
# 弱點曝光階段Lv2【設定】= 增加的傷害
Vulnerability2 = 30
# 弱點曝光階段Lv3【設定】= 增加的傷害
Vulnerability3 = 60


************騎士*****************

# 衝暈秒數
STUN_SEC = 2~5

#騎士 反擊屏障發動機率(%)
BARRIERchance = 33

#反擊屏障傷害倍率
Counterattack = 2

#衝擊之暈(設定=攻擊者等級小於被攻擊者，攻擊者等級等於被攻擊者，攻擊者等級大於等於被攻擊者)
ImpactHalo1 = 20
ImpactHalo2 = 40
ImpactHalo3 = 60

************妖精*****************

# 三重矢原始傷害倍率
TripleArrowDmg = 1.0

# 敏捷大於多少三重矢強化
# 強化後的三重矢是依照敏捷 / 100 去加成
# 例如設置180 = 三重矢傷害 * 1.8
TripleArrowDex = 180

#精準目標倍率 (仿正1-3)
STRIKER_DMG = 1

#精準射擊傷害倍率 
STRIKER_DMG2 = 1.2

#烈焰之魂倍率
SOUL_OF_FLAME_DAMAGE = 1.5

#精準射擊命中機率設定
#攻擊者等級小於被攻擊者
Precision1 = 20
#攻擊者等級 等於 被攻擊者
Precision2 = 40
#攻擊者等級大於等於被攻擊者
Precision3 = 60


*************黑妖****************


#黑妖 燃燒鬥志發動機率(%)
BURNINGSPIRITchance = 33

#黑妖 燃燒鬥志傷害倍率( ps.設置 15 為 1.5 倍 )
BURNINGSPIRITdmg = 13


#黑妖 雙重破壞傷害倍率(說明:設置1.8為1.8倍 )
Double_Brake_Dmg = 1.5

#黑妖 破壞盔甲傷害倍率(說明:設置0.58為額外加0.58%傷害)
Armor_Break_Dmg = 0.58

#破壞盔甲命中機率設定
#攻擊者等級小於被攻擊者
Damage1 = 20
#攻擊者等級 等於 被攻擊者
Damage2 = 40
#攻擊者等級大於等於被攻擊者
Damage3 = 60


************戰士*****************


#戰士魔法 泰坦:子彈 泰坦:魔法 泰坦:岩石 血量低於多少%才發動(正服設定40%)
Warrior_Magic = 40

#戰士魔法 (泰坦: 魔法)反彈機率(50=50%)
isPassive_Tatin_Magic = 30

#戰士魔法 (泰坦: 岩石)反彈機率(50=50%)
isPassive_Tatin_Rock = 30

#戰士魔法 (泰坦: 子彈)反彈機率(50=50%)
isPassive_Tatin_Bullet = 30

#戰士魔法 (粉碎)
isPassive_Tatin_CRASH = 10

#戰士魔法 (狂暴)
isPassive_Tatin_FURY = 10


*********個職業傷害倍率************

 **********王族***********

#當 王族 攻擊 王族 增加傷害倍率
Crown1 = 1.0
#當 王族 攻擊 騎士 增加傷害倍率
Crown2 = 1.0
#當 王族 攻擊 妖精 增加傷害倍率
Crown3 = 1.0
#當 王族 攻擊 法師 增加傷害倍率
Crown4 = 1.0
#當 王族 攻擊 黑妖 增加傷害倍率
Crown5 = 1.0
#當 王族 攻擊 龍騎士 增加傷害倍率
Crown6 = 1.0
#當 王族 攻擊 幻術師 增加傷害倍率
Crown7 = 1.0
#當 王族 攻擊 狂戰士 增加傷害倍率
Crown8 = 1.0

 **********騎士***********

#當 騎士 攻擊 王族 增加傷害倍率
Knight1 = 1.0
#當 騎士 攻擊 騎士 增加傷害倍率
Knight2 = 1.0
#當 騎士 攻擊 妖精 增加傷害倍率
Knight3 = 1.0
#當 騎士 攻擊 法師 增加傷害倍率
Knight4 = 1.0
#當 騎士 攻擊 黑妖 增加傷害倍率
Knight5 = 1.0
#當 騎士 攻擊 龍騎士 增加傷害倍率
Knight6 = 1.0
#當 騎士 攻擊 幻術師 增加傷害倍率
Knight7 = 1.0
#當 騎士 攻擊 狂戰士 增加傷害倍率
Knight8 = 1.0

 **********妖精***********

#當 妖精 攻擊 王族 增加傷害倍率
Elf1 = 1.0
#當 妖精 攻擊 騎士 增加傷害倍率
Elf2 = 1.0
#當 妖精 攻擊 妖精 增加傷害倍率
Elf3 = 1.0
#當 妖精 攻擊 法師 增加傷害倍率
Elf4 = 1.0
#當 妖精 攻擊 黑妖 增加傷害倍率
Elf5 = 1.0
#當 妖精 攻擊 龍騎 士增加傷害倍率
Elf6 = 1.0
#當 妖精 攻擊 幻術 師增加傷害倍率
Elf7 = 1.0
#當 妖精 攻擊 狂戰 士增加傷害倍率
Elf8 = 1.0

 **********法師*********** 

#當 法師 攻擊 王族 增加傷害倍率
Wizard1 = 1.0
#當 法師 攻擊 騎士 增加傷害倍率
Wizard2 = 1.0
#當 法師 攻擊 妖精 增加傷害倍率
Wizard3 = 1.0
#當 法師 攻擊 法師 增加傷害倍率
Wizard4 = 1.0
#當 法師 攻擊 黑妖 增加傷害倍率
Wizard5 = 1.0
#當 法師 攻擊 龍騎士 增加傷害倍率
Wizard6 = 1.0
#當 法師 攻擊 幻術師 增加傷害倍率
Wizard7 = 1.0
#當 法師 攻擊 狂戰士 增加傷害倍率
Wizard8 = 1.0

 **********黑妖***********

#當 黑妖 攻擊 王族 增加傷害倍率
Darkelf1 = 1.0
#當 黑妖 攻擊 騎士 增加傷害倍率
Darkelf2 = 1.0
#當 黑妖 攻擊 妖精 增加傷害倍率
Darkelf3 = 1.0
#當 黑妖 攻擊 法師 增加傷害倍率
Darkelf4 = 1.0
#當 黑妖 攻擊 黑妖 增加傷害倍率
Darkelf5 = 1.0
#當 黑妖 攻擊 龍騎士 增加傷害倍率
Darkelf6 = 1.0
#當 黑妖 攻擊 幻術師 增加傷害倍率
Darkelf7 = 1.0
#當 黑妖 攻擊 狂戰士 增加傷害倍率
Darkelf8 = 1.0

 **********龍騎士***********

#當 龍騎士 攻擊 王族 增加傷害倍率
DragonKnight1 = 1.0
#當 龍騎士 攻擊 騎士 增加傷害倍率
DragonKnight2 = 1.0
#當 龍騎士 攻擊 妖精 增加傷害倍率
DragonKnight3 = 1.0
#當 龍騎士 攻擊 法師 增加傷害倍率
DragonKnight4 = 1.0
#當 龍騎士 攻擊 黑妖 增加傷害倍率
DragonKnight5 = 1.0
#當 龍騎士 攻擊 龍騎士 增加傷害倍率
DragonKnight6 = 1.0
#當 龍騎士 攻擊 幻術師 增加傷害倍率
DragonKnight7 = 1.0
#當 龍騎士 攻擊 狂戰士 增加傷害倍率
DragonKnight8 = 1.0

 **********幻術師***********

#當 幻術師 攻擊 王族 增加傷害倍率
Illusionist1 = 1.0
#當 幻術師 攻擊 騎士 增加傷害倍率
Illusionist2 = 1.0
#當 幻術師 攻擊 妖精 增加傷害倍率
Illusionist3 = 1.0
#當 幻術師 攻擊 法師 增加傷害倍率
Illusionist4 = 1.0
#當 幻術師 攻擊 黑妖 增加傷害倍率
Illusionist5 = 1.0
#當 幻術師 攻擊 龍騎士 增加傷害倍率
Illusionist6 = 1.0
#當 幻術師 攻擊 幻術師 增加傷害倍率
Illusionist7 = 1.0
#當 幻術師 攻擊 狂戰士 增加傷害倍率
Illusionist8 = 1.0

 **********狂戰士***********

#當 狂戰士 攻擊 王族 增加傷害倍率
Warrior1 = 1.0
#當 狂戰士 攻擊 騎士 增加傷害倍率
Warrior2 = 1.0
#當 狂戰士 攻擊 妖精 增加傷害倍率
Warrior3 = 1.0
#當 狂戰士 攻擊 法師 增加傷害倍率
Warrior4 = 1.0
#當 狂戰士 攻擊 黑妖 增加傷害倍率
Warrior5 = 1.0
#當 狂戰士 攻擊 龍騎士 增加傷害倍率
Warrior6 = 1.0
#當 狂戰士 攻擊 幻術師 增加傷害倍率
Warrior7 = 1.0
#當 狂戰士 攻擊 狂戰士 增加傷害倍率
Warrior8 = 1.0

************轉生技能強化設定************
#王族-二轉：精準目標傷害增加10%(原本1倍)(設0.0關閉)
C2 = 0.0
#王族-四轉：勇猛意志隨機傷害提升為2倍(原本1.5倍)(設1.5關閉)
C4 = 1.5
#騎士-二轉：衝擊之暈秒數增加一秒(原本1~5秒)(設0關閉)
K2 = 1
#騎士-四轉：反擊屏障機率增加10%(原本35%)(設0關閉)
K4 = 10
#法師-二轉：聖結界施放變為施法對象周圍X格都有效果 (設0關閉)
W2 = 1
#法師-四轉：究光跟流星雨傷害提升X% (設定1.1為增加10%傷害) (設1.0關閉)
W4 = 1.1
#妖精-二轉：三重矢傷害倍率提升10% (設1.0關閉)
E2TRIPLE_ARROW = 1.1
#妖精-二轉：屬性之火近距離隨機傷害提升為2倍(原本1.5倍) (設1.5關閉)
E2ELEMENTAL_FIRE = 2.0
#妖精-四轉：精準射擊傷害提升10% (設1.0關閉)
E4STRIKER_GALE = 1.1
#妖精-四轉：烈焰之魂傷害倍率提升x倍 設定0.2表示原本(烈焰之魂倍率SOUL_OF_FLAME_DAMAGE)再+0.2 等於是設定額外加X%傷害值意思 (設0.0關閉)
E4SOUL_OF_FLAME = 0.2
#妖精-四轉：生祝補血量提升10% (設1.0關閉)
E4NATURES_BLESSING = 1.1
#黑妖-二轉：燃燒鬥志發動機率提升10%(原本33%)(設0關閉)
D2 = 10
#黑妖-四轉：雙重破壞傷害倍率提升為2倍(原本1.8倍)設定0.2表示原本1.8+0.2=2倍 等於是設定額外加X%傷害值意思 (設0.0關閉)
D4=0.2
#龍騎士-二轉：弱點曝光額外增加多少傷害,這邊為原本傷害再加額外轉生傷害 DK2weaknss1(第一階段) (設0關閉)
DK2weaknss1 = 10
#龍騎士-二轉：弱點曝光額外增加多少傷害,這邊為原本傷害再加額外轉生傷害 DK2weaknss2(第二階段) (設0關閉)
DK2weaknss2 = 15
#龍騎士-二轉：弱點曝光額外增加多少傷害,這邊為原本傷害再加額外轉生傷害 DK2weaknss3(第三階段) (設0關閉)
DK2weaknss3 = 20
#龍騎士-四轉：屠宰者追加15%機率衝暈一秒 (DK4SHOCKTIME 表示衝暈秒數) (設0關閉)
DK4RANDOM = 15
#龍騎士-四轉：屠宰者追加15%機率衝暈一秒 (DK4SHOCKTIME 表示衝暈秒數) (設0關閉)
DK4SHOCKTIME = 1
#幻術-二轉：奇古獸攻擊傷害增加10%  (設0.0關閉)
IS2 = 0.1
#幻術-四轉：化身傷害提升為1.5倍(原本1.3倍)(設0.0關閉)
IS4 = 0.2
#戰士-二轉：粉碎 狂暴 發動率提升為20%(原本10%)
WHYW2 = 10
#戰士-四轉：泰坦魔法發動血量提升為80%就發動(原本60%)
WHYW4 = 10

************以下暫無作用請勿刪除(若刪除模擬器將無法開啟!!)************************************************************************************************

#X重史技能次數為幾次? (技能編號設置1132)#暫無作用請勿刪除
ElfThree = 5

#反擊屏障是否對拿弓三格內進行反擊 #暫無作用請勿刪除
elfisBARRIER = true

#不疊加充暈時間為幾秒(技能編號設置1087)#暫無作用請勿刪除
SHOCK1TIME = 2


# 木乃伊秒數 #暫無作用請勿刪除
CURSE_SEC = 3~6


#防無延遲的技能 (NO_CD = null 可關閉) (逗點隔開技能編號)  #暫無作用請勿刪除
87,187,192,74,70,59,77,208,174,164,157,28,25,10,22,45,46,50,49,63,65,33,44,66,71,64,189,146,188,183,193,40,218,37,132,31

#不可疊加的技能 (HAS_SKILL = null 可關閉) (逗點隔開技能編號) #暫無作用請勿刪除
HAS_SKILL = 148,204,21,149,151,209,219,42,26,114,115,117,216,175,148,163