#-------------------------------------------------------------
# SQL config
#-------------------------------------------------------------

# ?????????
Driver_LOGIN = org.mariadb.jdbc.Driver

# ?????(?????)
URL1_LOGIN = jdbc:mariadb://localhost:3306/

# ?????(?????)
URL2_LOGIN = 880v2

# ??????(?????)
URL3_LOGIN = ?useUnicode=true&characterEncoding=utf8

# ??? ????(?????)
Login_LOGIN = root

# ??? ????(?????)
Password_LOGIN = root

# ?????(?????)
URL1 = jdbc:mariadb://localhost:3306/

# ?????(?????)
URL2 = 880v2

# ??????(?????)
URL3 = ?useUnicode=true&characterEncoding=utf8

# ??? ????(?????)
Login = root

# ??? ????(?????)
Password = root